def display_report(student):
    print()
    print("--- Student Report ---")
    print("ID      :", student.id)
    print("Name    :", student.name)
    print("Program :", student.program)
    print("Semester:", student.semester)
    print("Marks   :", student.marks)
    print("Grade   :", student.grade)
    print("Status  :", student.status)
    print()
